variables:
  API_REPO_URL: "https://t-dev.epitest.eu/MAR_18/T-DEV-702-Api"
  API_BRANCH: "prod"
  DOCKER_IMAGE_NAME: "api-image"
  DOCKER_COMPOSE_FILE: "docker-compose.prod.yml"

test_docker:
  stage: test
  tags:
    - sigaTagRunner 
  script:
    - docker run -d --name my-nginx-container nginx
    - docker ps -a
    - docker logs my-nginx-container 
    - ls -l /var/run/docker.sock
  only:
    - feature/docker-configuration-siga  
