stages:
  - clone
  - build


variables:
  API_REPO_URL: "t-dev.epitest.eu/MAR_18/T-DEV-702-Api.git api/"
  API_BRANCH: "feature/ci-config"
  DOCKER_IMAGE_NAME: "t-dev-702-api"
  ENVIRONMENT: "prod" 

clone_api:
  stage: clone
  tags:
    - sigaTagRunner
  script:
    - echo "Current working directory:"
    - pwd
    - echo "Cloning the API repository..."
    - git clone --branch ${API_BRANCH} https://anthony.guarneri:${PERSONAL_ACCESS_TOKEN}@${API_REPO_URL}
    - echo "Listing files in the current directory:"
    - ls -l
    - echo "Listing files in the cloned 'api' directory:"
    - ls -l api/api  # Si le répertoire 'api' est à l'intérieur du répertoire 'api/'


build_docker_image_dev:
  stage: build
  needs:
    - clone_api
  tags:
    - sigaTagRunner
  script:
    - echo "Building Docker image for development..."
    - cd api/api  # Naviguer vers le bon répertoire
    - docker build -t ${DOCKER_IMAGE_NAME}:dev -f Dockerfile.dev .
  rules:
    - if: '$ENVIRONMENT == "dev"'

build_docker_image_prod:
  stage: build
  needs:
    - clone_api
  tags:
    - sigaTagRunner
  script:
    - echo "Current working directory:"
    - pwd
    - echo "Listing files in the current directory:"
    - ls -l
    - echo "Listing files in the cloned 'api' directory:"
    - ls -l api/api 
    - echo "Building Docker image for production..."
    - cd api/api  # Naviguer vers le bon répertoire
    - docker build -t ${DOCKER_IMAGE_NAME}:prod -f Dockerfile.prod .
  rules:
    - if: '$ENVIRONMENT == "prod"'