stages:
  - install
  - build
  - test
  - deploy

# Variables globales
variables:
  NODE_ENV: 'production'
  DOCKER_HOST: "tcp://docker:2375/"
  DOCKER_TLS_CERTDIR: ""  

# Utilisation des runners Docker
default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache npm
    - npm install -g npm@latest

# Étape d'installation des dépendances pour le frontend
install_frontend:
  stage: install
  script:
    - echo "Installing frontend dependencies"
    - cd trinity
    - npm install
    - echo "Frontend dependencies installed"
  artifacts:
    paths:
      - trinity/node_modules
  only:
    - feature/docker-configuration-siga
    - main
    - dev

# Étape d'installation des dépendances pour le backend
install_backend:
  stage: install
  script:
    - echo "Installing backend dependencies"
    - cd app
    - npm install
    - echo "Backend dependencies installed"
  artifacts:
    paths:
      - app/node_modules
  only:
    - feature/docker-configuration-siga
    - main
    - dev

# Étape de build du frontend
build_frontend:
  stage: build
  script:
    - echo "Building frontend"
    - cd trinity
    - npm run build
    - echo "Frontend built successfully"
  artifacts:
    paths:
      - trinity/build
  only:
    - feature/docker-configuration-siga
    - main
    - dev

# Étape de tests pour le frontend
test_frontend:
  stage: test
  script:
    - echo "Running frontend tests"
    - cd trinity
    - npm test
    - echo "Frontend tests completed"
  only:
    - main
    - dev

# Étape de tests pour le backend
test_backend:
  stage: test
  script:
    - echo "Running backend tests"
    - cd app
    - npm test
    - echo "Backend tests completed"
  only:
    - feature/docker-configuration-siga
    - main
    - dev

# Étape de test simple pour vérifier le fonctionnement du runner
test_simple:
  stage: test
  script:
    - echo "Hello, GitLab Runner!"
  only:
    - feature/docker-configuration-siga
    - main
    - dev

# Étape de déploiement pour l'environnement de développement
deploy_dev:
  stage: deploy
  script:
  - echo "Attente pour le démarrage du service Docker"
  - |
    while ! docker info > /dev/null 2>&1; do
      echo "Docker n'est pas encore prêt, attente..."
      sleep 5
    done
  - docker-compose -f ./docker-compose.dev.yml up --build -d

  only:
    - feature/docker-configuration-siga
    - dev

# Étape de déploiement pour l'environnement de production
deploy_prod:
  stage: deploy
  script:
    - echo "Déploiement sur l'environnement de production"
    - docker-compose -f ./docker-compose.prod.yml up --build -d
  only:
    - feature/docker-configuration-siga
    - main
  when: manual  # Optionnel, pour le déploiement manuel en production 
