stages:
  - clone
  - build
  - test
  - deploy

before_script:
  - echo "Cleaning npm cache"
  - npm cache clean --force"
  - echo "SOURCE_REPO is $SOURCE_REPO"
  - |
    case "$SOURCE_REPO" in
      api)
        export REPO="api"
        ;;
      mobile)
        export REPO="mobile"
        ;;
      *)
        echo "Nom de dépôt non reconnu. Exiting."
        exit 1
        ;;
    esac
  - echo "REPO is set to $REPO"


# Variables de configuration
variables:
  API_REPO_URL: "t-dev.epitest.eu/MAR_18/T-DEV-702-Api.git"
  MOBILE_REPO_URL: "t-dev.epitest.eu/MAR_18/T-DEV-703-Mobile.git"
  
  DOCKER_IMAGE_NAME_API: "t-dev-702-api"
  DOCKER_IMAGE_NAME_MOBILE: "t-dev-703-mobile"
  API_BRANCH: "dev"  
  MOBILE_BRANCH: "dev-mobile"  
  ENV: "prod"  

# Étape de clonage des dépôts
clone_repos:
  stage: clone
  tags:
    - sigaRunner
  script:
    - echo "Determining the repository and branch to clone..."
    - if [ -d "app" ]; then rm -rf app; fi
    - |
      if [ "$REPO" == "api" ]; then
        export CLONE_URL="https://anthony.guarneri:${PERSONAL_ACCESS_TOKEN}@${API_REPO_URL}"
        if [ "$ENV" == "dev" ]; then
          export CLONE_BRANCH="dev"
        elif [ "$ENV" == "prod" ]; then
          export CLONE_BRANCH="dev"
        else
          echo "Invalid environment specified for API. Exiting."
          exit 1
        fi
      elif [ "$REPO" == "mobile" ]; then
        export CLONE_URL="https://anthony.guarneri:${PERSONAL_ACCESS_TOKEN}@${MOBILE_REPO_URL}"
        if [ "$ENV" == "dev" ]; then
          export CLONE_BRANCH="dev"
        elif [ "$ENV" == "prod" ]; then
          export CLONE_BRANCH="dev"
        else
          echo "Invalid environment specified for Mobile. Exiting."
          exit 1
        fi
      else
        echo "No valid repository specified. Exiting."
        exit 1
      fi
    - echo "Cloning from $CLONE_URL on branch $CLONE_BRANCH..."
    - git clone --branch $CLONE_BRANCH $CLONE_URL .
    - echo "Listing files in the current directory:"
    - ls -l
    - echo "Listing files in the cloned repository directory:"
    - ls -l app
  artifacts:
    paths:
      - .

  

# Build API ou Mobile en fonction de l'environnement
build_api_or_mobile:
  stage: build
  needs:
    - clone_repos
  tags:
    - sigaRunner
  script:
    - |
      if [ "$REPO" == "api" ]; then
        if [ "$ENV" == "dev" ]; then
          echo "Building and starting services for the API in dev environment using docker-compose..."
          docker-compose -f app/docker-compose.yml up --build -d app
        elif [ "$ENV" == "prod" ]; then
          echo "Building and starting services for the API in prod environment using docker-compose..."
          docker-compose -f app/docker-compose.yml up --build -d app
        else
          echo "Unknown environment for API, exiting..."
          exit 1
        fi
      elif [ "$REPO" == "mobile" ]; then
        if [ "$ENV" == "dev" ]; then
          echo "Building and starting services for the Mobile in dev environment using docker-compose..."
          docker-compose -f app/docker-compose.yml up --build -d mobile
        elif [ "$ENV" == "prod" ]; then
          echo "Building and starting services for the Mobile in prod environment using docker-compose..."
          docker-compose -f app/docker-compose.yml up --build -d mobile
        else
          echo "Unknown environment for Mobile, exiting..."
          exit 1
        fi
      else
        echo "Unknown repository, exiting..."
        exit 1
      fi
  rules:
    - if: '$ENV == "dev" || $ENV == "prod"'


# Tests pour l'API
test_api:
  stage: test
  needs:
    - build_api_or_mobile
  tags:
    - sigaRunner
  script:
    - echo "Running tests for the API..."
    - docker run --rm ${DOCKER_IMAGE_NAME_API}:${ENV} npm run test
  rules:
    - if: '($REPO == "api") && ($ENV == "prod")'

# Tests pour le Mobile
test_mobile:
  stage: test
  needs:
    - build_api_or_mobile
  tags:
    - sigaRunner
  script:
    - echo "Running tests for the Mobile..."
    - docker run --rm ${DOCKER_IMAGE_NAME_MOBILE}:${ENV} npm run test
  rules:
    - if: '($REPO == "mobile") && ($ENV == "prod")'

## Déploiement en développement pour l'API
deploy_api_dev:
  stage: deploy
  needs:
    - test_api
  tags:
    - sigaRunner
  script:
    - echo "Deploying API to development..."
    - docker run -d --name ${DOCKER_IMAGE_NAME_API}_dev -p 3000:3000 ${DOCKER_IMAGE_NAME_API}:dev
    - echo "API is deployed to development."
  rules:
    - if: '$ENV == "dev" && $REPO == "api"'

# Déploiement en développement pour le Mobile
deploy_mobile_dev:
  stage: deploy
  needs:
    - test_mobile
  tags:
    - sigaRunner
  script:
    - echo "Deploying Mobile to development..."
    - docker run -d --name ${DOCKER_IMAGE_NAME_MOBILE}_dev -p 4000:4000 ${DOCKER_IMAGE_NAME_MOBILE}:dev
    - echo "Mobile app is deployed to development."
  rules:
    - if: '$ENV == "dev" && $REPO == "mobile"'

# Déploiement en production pour l'API
deploy_api_prod:
  stage: deploy
  needs:
    - test_api
  tags:
    - sigaRunner
  script:
    - echo "Deploying API to production..."
    - docker run -d --name ${DOCKER_IMAGE_NAME_API}_prod -p 3000:3000 ${DOCKER_IMAGE_NAME_API}:prod
    - echo "API is deployed to production."
  rules:
    - if: '$ENV == "prod" && $REPO == "api"'

# Déploiement en production pour le Mobile
deploy_mobile_prod:
  stage: deploy
  needs:
    - test_mobile
  tags:
    - sigaRunner
  script:
    - echo "Deploying Mobile to production..."
    - docker run -d --name ${DOCKER_IMAGE_NAME_MOBILE}_prod -p 4000:4000 ${DOCKER_IMAGE_NAME_MOBILE}:prod
    - echo "Mobile app is deployed to production."
  rules:
    - if: '$ENV == "prod" && $REPO == "mobile"'
