variables:
  API_REPO_URL: "t-dev.epitest.eu/MAR_18/T-DEV-702-Api.git api/"
  API_BRANCH: "feature/ci-config"

test_docker:
  stage: test
  tags:
    - sigaTagRunner 
  script:
    - git clone --branch ${API_BRANCH} https://anthony.guarneri:${PERSONAL_ACCESS_TOKEN}@${API_REPO_URL}
    # Vérification du contenu du répertoire cloné
    echo "Listing files in the cloned repository:"
    ls -l api
    # Vérification de la présence de certains fichiers spécifiques
    echo "Checking if README.md exists:"
    ls -l api/README.md
  only:
    - feature/docker-configuration-siga  


