variables:
  API_REPO_URL: "t-dev.epitest.eu/MAR_18/T-DEV-702-Api.git api/"
  API_BRANCH: "feature/ci-config"

test_docker:
  stage: test
  tags:
    - sigaTagRunner 
  script:
    - echo "Current working directory:"
    - pwd  # Affiche le répertoire de travail actuel
    - echo "Triggering pipeline in DevOps repository..."
    - git clone --branch ${API_BRANCH} https://anthony.guarneri:${PERSONAL_ACCESS_TOKEN}@${API_REPO_URL}
    - echo "Listing files in the current directory:"
    - ls -l  # Affiche les fichiers dans le répertoire actuel
    - echo "Listing files in the 'api' directory:"
    - ls -l api  # Vérifie si le répertoire 'api' existe et contient des fichiers
  only:
    - feature/docker-configuration-siga  


