stages:
  - clone
  - build


variables:
  API_REPO_URL: "t-dev.epitest.eu/MAR_18/T-DEV-702-Api.git api/"
  API_BRANCH: "feature/ci-config"
  DOCKER_IMAGE_NAME: "t-dev-702-api"
  ENVIRONMENT: "prod" 

clone_api:
  stage: clone
  tags:
    - sigaTagRunner 
  script:
    - echo "Current working directory:"
    - pwd  
    - echo "Triggering pipeline in DevOps repository..."
    - git clone --branch ${API_BRANCH} https://anthony.guarneri:${PERSONAL_ACCESS_TOKEN}@${API_REPO_URL}
    - echo "Listing files in the current directory:"
    - ls -l  
    - echo "Listing files in the 'api' directory:"
    - ls -l api   
    - echo ${ENVIRONMENT}
  only:
    - feature/docker-configuration-siga  


build_docker_image_dev:
  stage: build
  needs:
    - clone_api
  tags:
    - sigaTagRunner
  script:
    - echo "Building Docker image for development..."
    - docker build -t ${DOCKER_IMAGE_NAME}:dev -f api/Dockerfile.dev api/
  rules:
    - if: '$ENVIRONMENT == "dev"'

build_docker_image_prod:
  stage: build
  needs:
    - clone_api
  tags:
    - sigaTagRunner
  script:
    - echo "Building Docker image for production..."
    - docker build -t ${DOCKER_IMAGE_NAME}:prod -f api/Dockerfile.prod api/
  rules:
    - if: '$ENVIRONMENT == "prod"'

