stages:
  - clone
  - build
  - deploy


variables:
  API_REPO_URL: "t-dev.epitest.eu/MAR_18/T-DEV-702-Api.git api/"
  API_BRANCH: "feature/ci-config"
  DOCKER_IMAGE_NAME: "t-dev-702-api"
  ENVIRONMENT: "" 

clone_api:
  stage: clone
  tags:
    - sigaRunner
  script:
    - echo "Current working directory:"
    - pwd
    - echo "Cloning the API repository..."
    - git clone --branch ${API_BRANCH} https://anthony.guarneri:${PERSONAL_ACCESS_TOKEN}@${API_REPO_URL}
    - echo "Listing files in the current directory:"
    - ls -l
    - echo "Listing files in the cloned 'api' directory:"
    - ls -l api
  artifacts:
    paths:
      - api  


build_docker_image_dev:
  stage: build
  needs:
    - clone_api
  tags:
    - sigaRunner
  script:
    - echo "Building Docker image for development..."
    - ls -l api/api
    - docker build --no-cache  -t ${DOCKER_IMAGE_NAME}:dev -f api/api/Dockerfile.dev api/api/
    # Cest pas plutot un docker compose ?
  rules:
    - if: '$ENVIRONMENT == "dev"'

build_docker_image_prod:
  stage: build
  needs:
    - clone_api
  tags:
    - sigaRunner
  script:
    - echo "Building Docker image for production..."
    - ls -l api/api
    - docker build -t ${DOCKER_IMAGE_NAME}:prod -f api/api/Dockerfile.prod api/api/
  rules:
    - if: '$ENVIRONMENT == "prod"'


deploy_docker_prod:
  stage: deploy
  needs:
    - build_docker_image_prod
  tags:
    - sigaRunner
  script:
    - echo "Starting Docker container for production with persistent data..."
    - docker volume create ${DOCKER_IMAGE_NAME}_prod_volume
    - docker run -d --name ${DOCKER_IMAGE_NAME}_prod -p 80:80 -v ${DOCKER_IMAGE_NAME}_prod_volume:/data ${DOCKER_IMAGE_NAME}:prod tail -f /dev/null
    - echo "Container is running in detached mode with persistent volume."
  rules:
    - if: '$ENVIRONMENT == "prod"'  