stages:
  - trigger_mobile
  - trigger_api
  - install
  - build
  - deploy

variables:
  NODE_ENV: 'production'
  DOCKER_HOST: "tcp://docker:2375/"
  DOCKER_TLS_CERTDIR: ""

default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "Installing base dependencies..."
    - apk add --no-cache npm git
    - npm install -g npm@latest

trigger_mobile_pipeline:
  stage: trigger_mobile
  trigger:
    project: MAR_18/T-DEV-703-mobile
    branch: main
    strategy: depend
  only:
    - main
    - dev
    - feature/docker-configuration-siga

trigger_api_pipeline:
  stage: trigger_api
  trigger:
    project: MAR_18/T-DEV-702-api
    branch: main
    strategy: depend
  only:
    - main
    - dev
    - feature/docker-configuration-siga

install_dependencies:
  stage: install
  script:
    - echo "Starting dependency installation..."
    - apk add --no-cache curl unzip
    - echo "Downloading mobile artifacts from project ${MOBILE_PROJECT_ID}..."
    - 'curl -v --header "PRIVATE-TOKEN: ${ACCESS_TOKEN}" "https://gitlab.com/api/v4/projects/${MOBILE_PROJECT_ID}/jobs/artifacts/feature/ci-config/download?job=build_mobile" -o mobile_artifacts.zip || echo "Failed to download mobile artifacts"'
    - echo "Extracting mobile artifacts..."
    - 'unzip -v mobile_artifacts.zip -d mobile/ || echo "Failed to extract mobile artifacts"'
    - echo "Downloading API artifacts from project ${API_PROJECT_ID}..."
    - 'curl -v --header "PRIVATE-TOKEN: ${ACCESS_TOKEN}" "https://gitlab.com/api/v4/projects/${API_PROJECT_ID}/jobs/artifacts/feature/ci-config/download?job=build_api" -o api_artifacts.zip || echo "Failed to download API artifacts"'
    - echo "Extracting API artifacts..."
    - 'unzip -v api_artifacts.zip -d api/ || echo "Failed to extract API artifacts"'
    - echo "Showing directory contents:"
    - ls -la
    - echo "Installation complete"
  artifacts:
    paths:
      - mobile/
      - api/
  only:
    - main
    - dev
    - feature/docker-configuration-siga

build:
  stage: build
  script:
    - echo "Starting build stage..."
    - ls -la
    - echo "Building with docker-compose..."
    - docker-compose -f docker-compose.yml build
    - echo "Build completed"
  only:
    - main
    - dev
    - feature/docker-configuration-siga

deploy_dev:
  stage: deploy
  script:
    - echo "Starting development deployment..."
    - ls -la
    - echo "Deploying with docker-compose..."
    - docker-compose -f docker-compose.dev.yml up --build -d
    - echo "Development deployment completed"
  only:
    - dev
    - feature/docker-configuration-siga

deploy_prod:
  stage: deploy
  script:
    - echo "Starting production deployment..."
    - ls -la
    - echo "Deploying with docker-compose..."
    - docker-compose -f docker-compose.prod.yml up --build -d
    - echo "Production deployment completed"
  only:
    - main
  when: manual

deploy_prod:
  stage: deploy
  script:
    - echo "Starting production deployment..."
    - ls -la
    - echo "Deploying with docker-compose..."
    - docker-compose -f docker-compose.prod.yml up --build -d
    - echo "Production deployment completed"
  only:
    - main
  when: manual