stages:
  - install
  - build
  - test
  - deploy

# Variables globales
variables:
  NODE_ENV: 'production'

# Utilisation des runners Docker
default:
  image: node:18-alpine
  before_script:
    - npm install -g npm@latest

# Étape d'installation des dépendances pour le frontend
install_frontend:
  stage: install
  tags:
    - t-dev-700 
  script:
    - cd trinity
    - npm install
  artifacts:
    paths:
      - trinity/node_modules
  only:
    - main
    - dev

# Étape d'installation des dépendances pour le backend
install_backend:
  stage: install
  script:
    - cd app
    - npm install
  artifacts:
    paths:
      - app/node_modules
  only:
    - main
    - dev

# Étape de build du frontend
build_frontend:
  stage: build
  script:
    - cd trinity
    - npm run build
  artifacts:
    paths:
      - trinity/build
  only:
    - main
    - dev

# Étape de tests pour le frontend
test_frontend:
  stage: test
  script:
    - cd trinity
    - npm test
  only:
    - main
    - dev

# Étape de tests pour le backend
test_backend:
  stage: test
  script:
    - cd app
    - npm test
  only:
    - main
    - dev

# Étape de test simple pour vérifier le fonctionnement du runner
test_simple:
  stage: test
  script:
    - echo "Hello, GitLab Runner!"
  only:
    - main
    - dev

# Étape de déploiement pour l'environnement de développement
deploy_dev:
  stage: deploy
  script:
    - echo "Déploiement sur l'environnement de développement"
    - docker-compose -f config/docker-compose.dev.yml up --build -d
  only:
    - dev

# Étape de déploiement pour l'environnement de production
deploy_prod:
  stage: deploy
  script:
    - echo "Déploiement sur l'environnement de production"
    - docker-compose -f config/docker-compose.prod.yml up --build -d
  only:
    - main
  when: manual  # Optionnel, pour le déploiement manuel en production
